### ISSUE TITLE
VSC properties - always read/write?

### ISSUE THREAD

**Issue by erikbosch** [COVESA/ifex#84]
In the [README](https://github.com/COVESA/vehicle_service_catalog/blob/master/README.md#namespace-list-object-properties) properties no longer has a type field, but it is still present in the [seat example service](https://github.com/COVESA/vehicle_service_catalog/blob/master/comfort-service.yml#L291):

```
    properties:
      - name: a_property # Will this be acceptable?
        description: A signal
        type: attribute # or sensor.
        datatype: uint8 # Native datatypes only?
```

In the README it says:

`Each properties list object specifies a shared state object that can be read and set, and which is available to all subscribing entities.`

So is the current intention that properties always shall be considered to be read/write in VSC? Or do we need extra information to cover that? Either like in the example using VSS terms (attribute/sensor/actuator), or by other means like `writeable: true`
